version: '2'

services:
    nginx:
        image: nginx:1.13.5
        ports:
            - 8001:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
        links:
            - redis
            - mysql

    mysql:
        image: mysql:8.0.3
        ports:
            - 33061:3306
        volumes:
            - ${BACKUP_PATH}/mysql/laravel-experiments:/var/lib/mysql

        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=laravel-experiments"

    redis:
        image: redis:5.0.4
        volumes:
          - ${BACKUP_PATH}/redis/laravel-experiments:/data
